theme: jekyll-theme-minimal
title: David Belenguer CV
logo: /assets/img/profile-pic.jpg
exclude:
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node
  - package.json
  - package-lock.json